name: release
on:
  push:
    branches:
      - "!*"
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u whyeasy --password-stdin
      - name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "whyeasy/sentry-exporter:${{ steps.get_version.outputs.VERSION }}"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
